version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run: mkdir test-reports
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install virtualenv
      - run: python3 -m virtualenv venv_test
      - run:
          name: "Install Python Dependencies in a venv"
          command: |
            source venv_test/bin/activate
            python3 -m pip install poetry
            poetry install
      - run:
          name: "Run Unit Tests"
          command: |
            source venv_test/bin/activate
            cd tests
            python -m unittest discover -v
workflows:
    build_test:
      jobs:
        - run_tests
