name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pylint-exit
    - name: Analysing the entire package with pylint
      run: |
        pylint --rcfile=./.github/pylintrc ./rlbenchplot/ || pylint-exit $?
        if [ $? -ne 0 ]; then
          echo "An error occurred while running pylint." >&2
          exit 1
        fi
    - name: Analysing the individual python files
      run: | 
        pylint --rcfile=./.github/pylintrc ./rlbenchplot/AgentsAnalytics.py || pylint-exit $?
        if [ $? -ne 0 ]; then
          echo "An error occurred while running pylint." >&2
          exit 1
        fi
        pylint --rcfile=./.github/pylintrc ./rlbenchplot/EpisodeDataExtractor.py || pylint-exit $?
        if [ $? -ne 0 ]; then
          echo "An error occurred while running pylint." >&2
          exit 1
        fi
        pylint --rcfile=./.github/pylintrc ./rlbenchplot/EpisodesDataTransformer.py || pylint-exit $?
        if [ $? -ne 0 ]; then
          echo "An error occurred while running pylint." >&2
          exit 1
        fi
